#!/usr/bin/env php
<?php
/**
 * Xzit Giggle
 *
 * This file `giggle.php` is part of the `xzit-giggle` project.
 * Xzit Giggle is available for use at your own risk and WITHOUT ANY WARRANTY.
 *
 * @license CC0 1.0 Universal
 * @website https://xzit.de/giggle
 * @author Sebastian Eiweleit <sebastian@eiweleit.de>
 * @since 07.11.2023
 */
declare(strict_types=1);

include_once __DIR__ . '/src/bin/main.php';